server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: eto-um
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:tabeldata.ip-dynamic.com}:${DATABASE_PORT:5432}/${DATABASE_NAME:ewallet}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:passwordnyaPostgres}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:192.168.100.106}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:eto_test}
          jwk-set-uri: http://${KEYCLOAK_HOST:192.168.100.106}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:eto_test}/protocol/openid-connect/certs


